import type { Element, Properties, Root } from 'hast'
import type { Options as SanitizeOptions } from 'rehype-sanitize'
import type { Plugin } from 'unified'
import { visit } from 'unist-util-visit'

const MARKER_PROPERTY = 'dataDfCompilerBoundary'

interface CompilerElementSnapshot {
  tagName: string
  properties: Properties
}

export interface CompilerSanitizeBoundary {
  mark: Plugin<[], Root, Root>
  protect: Plugin<[], Root, Root>
  restore: Plugin<[], Root, Root>
  schema: SanitizeOptions
}

function classNames(properties: Properties) {
  const value: unknown = properties.className
  return Array.isArray(value) ? value.map(String) : typeof value === 'string' ? value.split(/\s+/) : []
}

function isCompilerOwned(node: Element) {
  const properties = node.properties ?? {}
  return (
    properties.id !== undefined ||
    properties.name !== undefined ||
    Object.keys(properties).some((name) => name.startsWith('dataDf')) ||
    classNames(properties).some((name) => name.startsWith('df-'))
  )
}

/**
 * Preserve trusted compiler contracts while the default rehype schema cleans
 * author HTML. This includes ids generated by remark-rehype: sanitizing those
 * ids a second time would break footnote references. Raw author HTML is not an
 * element until after `mark`, so its ids still receive the sanitizer's clobber
 * prefix. A per-render nonce prevents authored markup from forging the
 * temporary bridge, and only the exact compiler snapshots are restored.
 */
export function createCompilerSanitizeBoundary(defaultSchema: SanitizeOptions): CompilerSanitizeBoundary {
  const prefix = `df-${globalThis.crypto.randomUUID()}-`
  const snapshots = new Map<string, CompilerElementSnapshot>()
  let sequence = 0
  const markerPattern = new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\d+$`)
  const schema: SanitizeOptions = {
    ...defaultSchema,
    attributes: {
      ...defaultSchema.attributes,
      div: [...(defaultSchema.attributes?.div ?? []), [MARKER_PROPERTY, markerPattern]]
    }
  }

  const mark: Plugin<[], Root, Root> = () => (tree) => {
    visit(tree, 'element', (node) => {
      if (!isCompilerOwned(node)) return
      const marker = `${prefix}${sequence++}`
      snapshots.set(marker, {
        tagName: node.tagName,
        properties: { ...node.properties }
      })
      node.properties = { ...node.properties, [MARKER_PROPERTY]: marker }
    })
  }

  const protect: Plugin<[], Root, Root> = () => (tree) => {
    visit(tree, 'element', (node) => {
      const marker = node.properties?.[MARKER_PROPERTY]
      if (typeof marker !== 'string' || !snapshots.has(marker)) return
      // `div` is allowed by the default schema. Replacing only the trusted
      // shell lets author descendants continue through normal sanitization.
      node.tagName = 'div'
      node.properties = { [MARKER_PROPERTY]: marker }
    })
  }

  const restore: Plugin<[], Root, Root> = () => (tree) => {
    visit(tree, 'element', (node) => {
      const marker = node.properties?.[MARKER_PROPERTY]
      if (typeof marker !== 'string') return
      const snapshot = snapshots.get(marker)
      if (!snapshot) return
      node.tagName = snapshot.tagName
      node.properties = snapshot.properties
      snapshots.delete(marker)
    })
  }

  return { mark, protect, restore, schema }
}
