import { join } from 'node:path'
import { canofoldVersion } from '../version'
import { canofoldEnvDts } from './canofoldEnv'

const localizedTemplates: Record<string, { index: string; guide: string }> = {
  zh: {
    index: `---
title: 首页
description: Canofold 中文文档首页
---

# 欢迎使用 Canofold

这是一个由 Canofold 生成的静态技术文档项目。
`,
    guide: `---
title: 指南
description: Canofold 使用指南
---

# 指南

运行 \`canofold dev\` 开始本地预览。
`
  },
  en: {
    index: `---
title: Home
description: Canofold English documentation home
---

# Welcome to Canofold

This is a static technical documentation project generated by Canofold.
`,
    guide: `---
title: Guide
description: Canofold guide
---

# Guide

Run \`canofold dev\` to preview locally.
`
  }
}

const neutralIndex = `---
title: Canofold
description: Technical documentation built with Canofold
---

# Canofold
`

function localizedTemplateFor(locale: string) {
  return localizedTemplates[locale] ?? localizedTemplates[locale.toLowerCase().split('-')[0] ?? '']
}

function configTemplate(docsDir: string, defaultLocale: string, locales: string[]) {
  return `import { defineConfig } from 'canofold'

export default defineConfig({
  title: 'Canofold',
  description: 'Technical documentation',
  requiredVersion: '^${canofoldVersion}',
  docsDir: ${JSON.stringify(docsDir)},
  i18n: {
    defaultLocale: '${defaultLocale}',
    locales: [${locales.map((locale) => `'${locale}'`).join(', ')}]
  }
})
`
}

export function createInitFiles(options: {
  docsDir: string
  defaultLocale: string
  locales: string[]
  includeContent: boolean
  includeConfig: boolean
}) {
  const { docsDir, defaultLocale, locales, includeContent, includeConfig } = options
  const files: Record<string, string> = {
    [join(docsDir, 'canofold-env.d.ts')]: canofoldEnvDts
  }
  if (includeConfig) files['canofold.config.ts'] = configTemplate(docsDir, defaultLocale, locales)
  if (!includeContent) return files

  for (const locale of locales) {
    const prefix = locale === defaultLocale ? docsDir : join(docsDir, locale)
    const templates = localizedTemplateFor(locale)
    files[join(prefix, 'index.md')] = templates?.index ?? neutralIndex
    if (templates) files[join(prefix, 'guide.md')] = templates.guide
  }
  return files
}
