import { join } from 'node:path'
import { docfuseVersion } from '../version'
import { docfuseEnvDts } from './docfuseEnv'

const localizedTemplates: Record<string, { index: string; guide: string }> = {
  zh: {
    index: `---
title: 首页
description: Docfuse 中文文档首页
---

# 欢迎使用 Docfuse

这是一个由 Docfuse 生成的静态技术文档项目。
`,
    guide: `---
title: 指南
description: Docfuse 使用指南
---

# 指南

运行 \`docfuse dev\` 开始本地预览。
`
  },
  en: {
    index: `---
title: Home
description: Docfuse English documentation home
---

# Welcome to Docfuse

This is a static technical documentation project generated by Docfuse.
`,
    guide: `---
title: Guide
description: Docfuse guide
---

# Guide

Run \`docfuse dev\` to preview locally.
`
  }
}

const neutralIndex = `---
title: Docfuse
description: Technical documentation built with Docfuse
---

# Docfuse
`

function localizedTemplateFor(locale: string) {
  return localizedTemplates[locale] ?? localizedTemplates[locale.toLowerCase().split('-')[0] ?? '']
}

function configTemplate(docsDir: string, defaultLocale: string, locales: string[]) {
  return `import { defineConfig } from 'docfuse'

export default defineConfig({
  title: 'Docfuse',
  description: 'Technical documentation',
  requiredVersion: '^${docfuseVersion}',
  docsDir: ${JSON.stringify(docsDir)},
  i18n: {
    defaultLocale: '${defaultLocale}',
    locales: [${locales.map((locale) => `'${locale}'`).join(', ')}]
  }
})
`
}

export function createInitFiles(options: {
  docsDir: string
  defaultLocale: string
  locales: string[]
  includeContent: boolean
  includeConfig: boolean
}) {
  const { docsDir, defaultLocale, locales, includeContent, includeConfig } = options
  const files: Record<string, string> = {
    [join(docsDir, 'docfuse-env.d.ts')]: docfuseEnvDts
  }
  if (includeConfig) files['docfuse.config.ts'] = configTemplate(docsDir, defaultLocale, locales)
  if (!includeContent) return files

  for (const locale of locales) {
    const prefix = locale === defaultLocale ? docsDir : join(docsDir, locale)
    const templates = localizedTemplateFor(locale)
    files[join(prefix, 'index.md')] = templates?.index ?? neutralIndex
    if (templates) files[join(prefix, 'guide.md')] = templates.guide
  }
  return files
}
