import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

const tokensUrl = new URL('../tokens.css', import.meta.url)
const stylesUrl = new URL('../styles.css', import.meta.url)

describe('Markdown CSS entrypoints', () => {
  it('ships the shared palette and a borderless, compact geometry contract', async () => {
    const [tokens, styles] = await Promise.all([readFile(tokensUrl, 'utf8'), readFile(stylesUrl, 'utf8')])

    expect(tokens).toContain('--cf-accent-500: #0088ff')
    expect(tokens).toContain('--cf-info: #0088ff')
    expect(tokens).toContain('--cf-info-deep: #0088ff')
    expect(tokens).toContain('--cf-success: #34c759')
    expect(tokens).toContain('--cf-success-deep: #34c759')
    expect(tokens).toContain('--cf-warning: #ff8d28')
    expect(tokens).toContain('--cf-danger: #ff383c')
    expect(tokens).toContain('--cf-danger-deep: #ff383c')
    expect(tokens).toContain('--cf-yellow: #ffcc00')
    expect(tokens).toContain('--cf-body-font-size: 1rem')
    expect(tokens).toContain('--cf-body-line-height: 1.6')
    expect(tokens).toContain('--cf-heading-1-size: 2rem')
    expect(tokens).toContain('--cf-heading-2-size: 1.625rem')
    expect(tokens).toContain('--cf-heading-3-size: 1.375rem')
    expect(tokens).toContain('--cf-heading-4-size: 1.25rem')
    expect(tokens).toContain('--cf-heading-5-size: 1.125rem')
    expect(tokens).toContain('--cf-heading-6-size: 1.0625rem')
    expect(tokens).toContain('--cf-site-gutter: 2.25rem')
    expect(tokens).toContain('--cf-header-height: 4.25rem')
    expect(tokens).toContain('--cf-sidebar-width: 17.5rem')
    expect(tokens).toContain('--cf-outline-width: 18.75rem')
    expect(tokens).toContain('--cf-radius-lg: 8px')
    expect(tokens).not.toContain('9999px')
    expect(styles).toContain('.cf-content')
    expect(styles).toContain('.cf-content *::before')
    expect(styles).not.toMatch(/(^|\n)\*[,\n]/)
    expect(styles).toContain('font-size: var(--cf-heading-1-size)')
    expect(styles).toContain('font-size: var(--cf-heading-6-size)')
    expect(styles).toContain('line-height: calc(var(--cf-heading-line-height) + 0.05)')
    expect(styles).toContain('line-height: calc(var(--cf-heading-line-height) + 0.2)')
    expect(styles).toContain('.cf-callout')
    expect(tokens).not.toContain('--cf-callout-info')
    expect(styles).not.toMatch(/--cf-callout-tone:/)
    expect(styles).toContain('--cf-callout-tone-deep: var(--cf-success-deep)')
    expect(styles).toContain('--cf-block-padding: 0.875rem')
    expect(styles).toContain(
      '--cf-block-toolbar-surface: color-mix(in oklab, var(--cf-ink) 6%, var(--cf-surface-secondary))'
    )
    expect(styles).toContain('--cf-block-stage-surface: var(--cf-surface-soft)')
    expect(tokens).toContain('--cf-diagram-surface: var(--cf-surface-soft)')
    expect(tokens).toContain('--cf-diagram-accent: var(--cf-accent-500)')
    expect(styles).not.toContain('.cf-diagram-window')
    expect(styles).toContain('height: 1.2em')
    expect(styles).toContain('inset-inline-start: -1.75rem')
    expect(styles).toContain('var(--cf-ink-secondary) 12%')
    expect(styles).toContain(".cf-sort-button[data-sort='asc'] .cf-sort-icon path:nth-child(2)")
    expect(styles).toContain(".cf-sort-button[data-sort='desc'] .cf-sort-icon path:nth-child(1)")
    expect(styles).toContain('counter-reset: cf-code-line')
    expect(styles).toContain('counter-increment: cf-code-line')
    expect(styles).toContain('white-space: pre-wrap')
    expect(styles).toContain('line-height: 1.8')
    expect(styles).toContain('padding-inline: calc(2.75ch + 0.4rem) 0')
    expect(styles).toContain('.cf-table-window > .cf-block-toolbar')
    expect(styles).toContain('background: var(--cf-surface-elevated)')
    expect(styles).toContain('padding: 0 var(--cf-block-padding)')
    expect(styles).toContain('min-height: var(--cf-block-toolbar-height)')
    expect(styles).not.toContain('linear-gradient(')
  })
})
