import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

const tokensUrl = new URL('../tokens.css', import.meta.url)
const stylesUrl = new URL('../styles.css', import.meta.url)

describe('Markdown CSS entrypoints', () => {
  it('ships the shared palette and a borderless, compact geometry contract', async () => {
    const [tokens, styles] = await Promise.all([readFile(tokensUrl, 'utf8'), readFile(stylesUrl, 'utf8')])

    expect(tokens).toContain('--df-accent-500: #0088ff')
    expect(tokens).toContain('--df-info: #0088ff')
    expect(tokens).toContain('--df-info-deep: #0088ff')
    expect(tokens).toContain('--df-success: #34c759')
    expect(tokens).toContain('--df-success-deep: #34c759')
    expect(tokens).toContain('--df-warning: #ff8d28')
    expect(tokens).toContain('--df-danger: #ff383c')
    expect(tokens).toContain('--df-danger-deep: #ff383c')
    expect(tokens).toContain('--df-yellow: #ffcc00')
    expect(tokens).toContain('--df-body-font-size: 1rem')
    expect(tokens).toContain('--df-body-line-height: 1.6')
    expect(tokens).toContain('--df-heading-1-size: 2rem')
    expect(tokens).toContain('--df-heading-2-size: 1.625rem')
    expect(tokens).toContain('--df-heading-3-size: 1.375rem')
    expect(tokens).toContain('--df-heading-4-size: 1.25rem')
    expect(tokens).toContain('--df-heading-5-size: 1.125rem')
    expect(tokens).toContain('--df-heading-6-size: 1.0625rem')
    expect(tokens).toContain('--df-site-gutter: 2.25rem')
    expect(tokens).toContain('--df-header-height: 4.25rem')
    expect(tokens).toContain('--df-sidebar-width: 17.5rem')
    expect(tokens).toContain('--df-outline-width: 18.75rem')
    expect(tokens).toContain('--df-radius-lg: 8px')
    expect(tokens).not.toContain('9999px')
    expect(styles).toContain('.df-content')
    expect(styles).toContain('.df-content *::before')
    expect(styles).not.toMatch(/(^|\n)\*[,\n]/)
    expect(styles).toContain('font-size: var(--df-heading-1-size)')
    expect(styles).toContain('font-size: var(--df-heading-6-size)')
    expect(styles).toContain('line-height: calc(var(--df-heading-line-height) + 0.05)')
    expect(styles).toContain('line-height: calc(var(--df-heading-line-height) + 0.2)')
    expect(styles).toContain('.df-callout')
    expect(tokens).not.toContain('--df-callout-info')
    expect(styles).not.toMatch(/--df-callout-tone:/)
    expect(styles).toContain('--df-callout-tone-deep: var(--df-success-deep)')
    expect(styles).toContain('--df-block-padding: 0.875rem')
    expect(styles).toContain(
      '--df-block-toolbar-surface: color-mix(in oklab, var(--df-ink) 6%, var(--df-surface-secondary))'
    )
    expect(styles).toContain('--df-block-stage-surface: var(--df-surface-soft)')
    expect(tokens).toContain('--df-diagram-surface: var(--df-surface-soft)')
    expect(tokens).toContain('--df-diagram-accent: var(--df-accent-500)')
    expect(styles).not.toContain('.df-diagram-window')
    expect(styles).toContain('height: 1.2em')
    expect(styles).toContain('inset-inline-start: -1.75rem')
    expect(styles).toContain('var(--df-ink-secondary) 12%')
    expect(styles).toContain(".df-sort-button[data-sort='asc'] .df-sort-icon path:nth-child(2)")
    expect(styles).toContain(".df-sort-button[data-sort='desc'] .df-sort-icon path:nth-child(1)")
    expect(styles).toContain('counter-reset: df-code-line')
    expect(styles).toContain('counter-increment: df-code-line')
    expect(styles).toContain('white-space: pre-wrap')
    expect(styles).toContain('line-height: 1.8')
    expect(styles).toContain('padding-inline: calc(2.75ch + 0.4rem) 0')
    expect(styles).toContain('.df-table-window > .df-block-toolbar')
    expect(styles).toContain('background: var(--df-surface-elevated)')
    expect(styles).toContain('padding: 0 var(--df-block-padding)')
    expect(styles).toContain('min-height: var(--df-block-toolbar-height)')
    expect(styles).not.toContain('linear-gradient(')
  })
})
